#!/usr/bin/env bash
# Build StemForge.app — a double-clickable launcher for the local UI.
#
# The bundle does not embed Python. It records the path of the virtualenv it
# was built from and launches that, so the app stays small and the models
# stay in the shared Hugging Face cache.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="${VENV:-$ROOT/.venv}"
APP="${1:-$ROOT/dist/StemForge.app}"

if [[ ! -x "$VENV/bin/python" ]]; then
  echo "No virtualenv at $VENV — run 'make install' first, or set VENV=..." >&2
  exit 1
fi

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>StemForge</string>
  <key>CFBundleDisplayName</key><string>StemForge</string>
  <key>CFBundleIdentifier</key><string>app.stemforge.desktop</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>StemForge</string>
  <key>CFBundleIconFile</key><string>StemForge</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/StemForge" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make_app.sh — do not edit by hand.
PYTHON="$VENV/bin/python"
PORT=\${STEMFORGE_PORT:-8787}

if [[ ! -x "\$PYTHON" ]]; then
  osascript -e 'display alert "StemForge" message "The Python environment this app was built against is missing. Rebuild with scripts/make_app.sh." as critical'
  exit 1
fi

# Reuse an already-running instance rather than failing on a busy port.
if curl -sf "http://127.0.0.1:\$PORT/api/config" >/dev/null 2>&1; then
  open "http://127.0.0.1:\$PORT/"
  exit 0
fi

LOG="\$HOME/Library/Logs/StemForge.log"
mkdir -p "\$(dirname "\$LOG")"
exec "\$PYTHON" -m stemforge.cli serve --port "\$PORT" >>"\$LOG" 2>&1
LAUNCHER

chmod +x "$APP/Contents/MacOS/StemForge"

if [[ -f "$ROOT/scripts/StemForge.icns" ]]; then
  cp "$ROOT/scripts/StemForge.icns" "$APP/Contents/Resources/StemForge.icns"
fi

# An ad-hoc signature is enough for a locally built app and keeps Gatekeeper quiet.
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || true
touch "$APP"

echo "Built $APP"
